FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# cloudnativego

Test the cloud native go.

## Match Collection [/matches]

### List All Matched [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Start a New Match [POST]

Start a New Match.

+ Request (application/json)

        {
            "gridsize": 19,
            "players": [
                {
                    "color": "white",
                    "name": "bob"
                },
                {
                    "color": "black",
                    "name": "alfred"
                }
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /matches/5a003b78

    + Body

            {
                "id": "5a003b78",
                "started_at": "2015-08-05T08:40:51.620Z",
                "gridsize": 19,
                "turn": 0,
                "players": [
                    {
                        "color": "white",
                        "name": "bob",
                        "score": 10
                    }, {
                        "color": "black",
                        "name": "alfred",
                        "score": 22
                    }
                ]
            }